version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: czesci-zdania-frontend
    ports:
      - "8080:80" # Host:Container (frontend runs on port 80 in the Nginx container)
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: czesci-zdania-backend
    ports:
      - "3000:3000" # Assuming backend runs on port 3000
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend/src:/usr/src/app/src # Mount src for development
    networks:
      - app-network

# volumes: # Uncomment when db service is added
#   mongo_data: 

networks:
  app-network:
    driver: bridge

# volumes: # Uncomment when db service is added
#   mongo_data: 