version: '3.8'

services:
  frontend:
    image: nginx:1.25-alpine
    container_name: czesci-zdania-frontend
    ports:
      - "8080:80" # Assuming frontend runs on port 80 in the container
    volumes:
      - ./frontend/public:/usr/share/nginx/html # For static assets if serving directly
      # If using a build step for frontend (e.g., Vite), you'd mount the dist folder:
      # - ./frontend/dist:/usr/share/nginx/html 
    # depends_on:
    #   - backend # Uncomment if frontend needs backend to be up

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile # Assuming Dockerfile is in backend/
    container_name: czesci-zdania-backend
    image: czesci-zdania-backend-img 
    ports:
      - "3000:3000" # Assuming backend runs on port 3000
    environment:
      - NODE_ENV=development
      # - MONGO_URI=mongodb://db:27017/czesci_zdania # Uncomment when db service is added
      # - OPENAI_API_KEY=your_api_key_here # Add your OpenAI API key
    volumes:
      - ./backend/src:/usr/src/app/src # Mount src for development
    # depends_on:
    #   - db # Uncomment when db service is added
    # restart: unless-stopped # Optional: for production

  # db: # Uncomment and configure when MongoDB is needed (Post-MVP)
  #   image: mongo:7
  #   container_name: czesci-zdania-db
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db
  #   restart: unless-stopped

  # proxy: # Uncomment and configure when Nginx proxy is needed (Post-MVP)
  #   image: nginx:1.25-alpine
  #   container_name: czesci-zdania-proxy
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro # You'll need to create nginx.conf
  #   depends_on:
  #     - frontend
  #     - backend

# volumes: # Uncomment when db service is added
#   mongo_data: 